language: go
sudo: false

go:
  - 1.5.3
  - 1.6
  - tip

env:
  global:
    - GO15VENDOREXPERIMENT=1

#install: true
script:
  - make validate
  - make test
  - make bin

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - go: tip

